### ISSUE TITLE
There are no values of type Void

### ISSUE THREAD

**Issue by dalnefre** [tristanls/ex#1]
https://github.com/tristanls/ex/blob/ac82fbe27f9cd8ab30a1e1e77d707bea04641415/ex.js#L133

**Comment by dalnefre** [comment]
Unit has exactly one instance, called by various names like null, nil, (), <>, and in your case unit. Void, however, has no instances at all.

**Comment by tristanls** [comment]
Ah, thank you for pointing that out. Also, I didn't mean to invent yet another name for an instance of the Unit type. I just failed to distinguish between the name of the instance (which I'll change back to `null`) and the name of the type :)

**Comment by tristanls** [comment]
I think I've addressed your feedback in 43ec3ab.

**Comment by dalnefre** [comment]
Agreed. My issue is resolved. I'm glad you chose the name "null", since it matches JSON expectations.
