### ISSUE TITLE
We would like to express negative tests without requiring .not()

### ISSUE THREAD

**Issue by dalnefre** [tristanls/ex#2]
Negative tests could be refactored to use something like:

EX.deny= function deny(predicate, message)
{
    if (predicate !== EX.false)
    {
        throw new Error(message);
    }
}

This would allow tests to remain expressive without requiring boolean logic like a "not" property/method to be implemented first.

**Comment by tristanls** [comment]
Incorporated your feedback in 929ad96.

Also, there's an interesting "moment in time" insight from the `TODO: // Boolean type is currently indistinguishable` comment in the form of highlighting what is important for types to be meaningfully separate. That is, one ought to be able to do something separate with them. At least in the presented formulation.
